services:
  db:
    image: mysql:8.0
    container_name: taskmanager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskmanager
    ports:
      - "3306:3306"
    volumes:
      - db_database:/var/lib/mysql

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    # command: sh -c "npx prisma migrate deploy && node build/main.js"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TS_NODE_TRANSPILE_ONLY=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npx prisma migrate dev --name init && npm run start:dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - app
    working_dir: /workspace/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/workspace/frontend
      - /workspace/frontend/node_modules
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  db_database:
